# Generated by Django 2.2.16 on 2020-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200930_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='clave',
            field=models.CharField(default='dfspijgdf', max_length=10),
        ),
    ]
