# Generated by Django 2.2.16 on 2020-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201109_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estrellas',
            field=models.PositiveSmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'Tourist'), (4, 'Standard'), (5, 'Comfort'), (6, 'First Class'), (7, 'Luxury')], unique=True),
        ),
    ]
