# Generated by Django 3.1.1 on 2020-10-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200930_2350'),
        ('hotel', '0002_auto_20201005_1735'),
    ]

    operations = [
    ]
