# Generated by Django 2.2.16 on 2020-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_merge_20201019_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['cantidad_habitaciones']},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
