# Generated by Django 2.2.16 on 2020-11-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201109_1906'),
        ('hotel', '0004_auto_20201109_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='encargado',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Encargado'),
            preserve_default=False,
        ),
    ]
