# Generated by Django 2.2.16 on 2020-12-15 22:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.PositiveSmallIntegerField(default=101, validators=[django.core.validators.MinValueValidator(101), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='temporadaalta',
            name='inicio',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
