# Generated by Django 2.2.16 on 2020-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20200930_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fue_pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='habitaciones',
            field=models.ManyToManyField(related_name='alquileres', to='hotel.Habitacion'),
        ),
    ]
