# Generated by Django 2.2.16 on 2020-12-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_auto_20201210_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fue_pagado',
        ),
    ]
